// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZXVPV02YulBFxUJsyRRAloMAnR0NUmAM',
    appId: '1:678373855676:web:9f60e6821e754b6c8d5bb9',
    messagingSenderId: '678373855676',
    projectId: 'alumni-9f57e',
    authDomain: 'alumni-9f57e.firebaseapp.com',
    storageBucket: 'alumni-9f57e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxvEeio2Eb1spKaoCxK1wD9IQEObsQHWc',
    appId: '1:678373855676:android:0016644a660396918d5bb9',
    messagingSenderId: '678373855676',
    projectId: 'alumni-9f57e',
    storageBucket: 'alumni-9f57e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0fR7XXQn8Sd_WZCS3PHqcnSEatmnqbYs',
    appId: '1:678373855676:ios:a8147da17d0cd62e8d5bb9',
    messagingSenderId: '678373855676',
    projectId: 'alumni-9f57e',
    storageBucket: 'alumni-9f57e.firebasestorage.app',
    iosBundleId: 'com.example.alumni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0fR7XXQn8Sd_WZCS3PHqcnSEatmnqbYs',
    appId: '1:678373855676:ios:a8147da17d0cd62e8d5bb9',
    messagingSenderId: '678373855676',
    projectId: 'alumni-9f57e',
    storageBucket: 'alumni-9f57e.firebasestorage.app',
    iosBundleId: 'com.example.alumni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZXVPV02YulBFxUJsyRRAloMAnR0NUmAM',
    appId: '1:678373855676:web:4eac341ff87900a28d5bb9',
    messagingSenderId: '678373855676',
    projectId: 'alumni-9f57e',
    authDomain: 'alumni-9f57e.firebaseapp.com',
    storageBucket: 'alumni-9f57e.firebasestorage.app',
  );

}